# Generated by Django 2.0.6 on 2018-06-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=1000000500100900)),
                ('nazwisko', models.CharField(max_length=69)),
            ],
        ),
    ]
