# Generated by Django 2.0.6 on 2018-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spoldzielnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imie',
            field=models.CharField(max_length=96),
        ),
    ]
