# Generated by Django 2.0.6 on 2018-06-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spoldzielnia', '0002_auto_20180612_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
