# Generated by Django 2.0.6 on 2018-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spoldzielnia', '0005_auto_20180616_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
